import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sequencesRoot = path.join(root, "public", "sequences");
const outputFile = path.join(root, "src", "generated", "sequenceManifest.ts");

function humanizeZipName(filename) {
  const base = filename.replace(/\.zip$/i, "");
  return base
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function zipFilenameToId(filename) {
  return filename
    .replace(/\.zip$/i, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function generateSequenceManifest() {
  fs.mkdirSync(sequencesRoot, { recursive: true });
  const files = fs
    .readdirSync(sequencesRoot)
    .filter((name) => name.toLowerCase().endsWith(".zip"))
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));

  const manifest = files.map((file) => ({
    id: zipFilenameToId(file),
    label: humanizeZipName(file),
    file,
  }));

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(
    outputFile,
    `// Auto-generated by scripts/generateSequenceManifest.mjs — do not edit.

export type SequenceManifestEntry = {
  id: string;
  label: string;
  file: string;
};

export const SEQUENCE_MANIFEST: SequenceManifestEntry[] = ${JSON.stringify(manifest, null, 2)};
`,
  );

  return manifest;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const manifest = generateSequenceManifest();
  console.log(
    `Wrote ${manifest.length} sequence(s) to src/generated/sequenceManifest.ts`,
  );
}
